// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210123004715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Breed = "Short Hair",
                            Name = "Baby Girl"
                        },
                        new
                        {
                            CatId = 2,
                            Breed = "Short Hair",
                            Name = "Inky"
                        },
                        new
                        {
                            CatId = 3,
                            Breed = "Siamese",
                            Name = "Marley"
                        },
                        new
                        {
                            CatId = 4,
                            Breed = "Short Hair",
                            Name = "Michael"
                        },
                        new
                        {
                            CatId = 5,
                            Breed = "Short Hair",
                            Name = "Paprika"
                        },
                        new
                        {
                            CatId = 6,
                            Breed = "Long Hair",
                            Name = "Poe"
                        },
                        new
                        {
                            CatId = 7,
                            Breed = "Short Hair",
                            Name = "Brutus"
                        },
                        new
                        {
                            CatId = 8,
                            Breed = "Short Hair",
                            Name = "Ludo"
                        },
                        new
                        {
                            CatId = 9,
                            Breed = "Long Hair",
                            Name = "Nala"
                        },
                        new
                        {
                            CatId = 10,
                            Breed = "Siamese",
                            Name = "Turbo"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Breed = "Pit Bull",
                            Name = "Uma"
                        },
                        new
                        {
                            DogId = 2,
                            Breed = "Australian Cattledog",
                            Name = "Abner"
                        },
                        new
                        {
                            DogId = 3,
                            Breed = "Lab Mix",
                            Name = "Jackson"
                        },
                        new
                        {
                            DogId = 4,
                            Breed = "Australian Cattledog",
                            Name = "Aden"
                        },
                        new
                        {
                            DogId = 5,
                            Breed = "Lab Mix",
                            Name = "Meeks"
                        },
                        new
                        {
                            DogId = 6,
                            Breed = "Retriever",
                            Name = "Brett"
                        },
                        new
                        {
                            DogId = 7,
                            Breed = "Pit Bull",
                            Name = "Parker"
                        },
                        new
                        {
                            DogId = 8,
                            Breed = "Chihuahua",
                            Name = "Miss Precious"
                        },
                        new
                        {
                            DogId = 9,
                            Breed = "Pit Bull",
                            Name = "Chickie"
                        },
                        new
                        {
                            DogId = 10,
                            Breed = "German Sheppard",
                            Name = "Jasmine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
