// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CatId");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Breed = "Pit Bull",
                            Name = "Uma"
                        },
                        new
                        {
                            DogId = 2,
                            Breed = "Australian Cattledog",
                            Name = "Abner"
                        },
                        new
                        {
                            DogId = 3,
                            Breed = "Lab Mix",
                            Name = "Jackson"
                        },
                        new
                        {
                            DogId = 4,
                            Breed = "Australian Cattledog",
                            Name = "Aden"
                        },
                        new
                        {
                            DogId = 5,
                            Breed = "Lab Mix",
                            Name = "Meeks"
                        },
                        new
                        {
                            DogId = 6,
                            Breed = "Retriever",
                            Name = "Brett"
                        },
                        new
                        {
                            DogId = 7,
                            Breed = "Pit Bull",
                            Name = "Parker"
                        },
                        new
                        {
                            DogId = 8,
                            Breed = "Chihuahua",
                            Name = "Miss Precious"
                        },
                        new
                        {
                            DogId = 9,
                            Breed = "Pit Bull",
                            Name = "Chickie"
                        },
                        new
                        {
                            DogId = 10,
                            Breed = "German Sheppard",
                            Name = "Jasmine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
